<?php

    //matrice delle efficacie dei tipi (riga indica attaccante, colonna difensore)
    const efficacie = array(
        "normale" =>	array(
                            "normale" =>	1,
                            "fuoco" => 		1,
                            "acqua" => 		1,
                            "elettro" => 	1,
                            "erba" => 		1,
                            "ghiaccio" => 	1,
                            "lotta" => 		1,
                            "veleno" => 	1,
                            "terra" => 		1,
                            "volante" => 	1,
                            "psico" => 		1,
                            "coleottero" => 1,
                            "roccia" => 	0.5,
                            "spettro" => 	0,
                            "drago" => 		1,
                            "buio" => 		1,
                            "acciaio" =>	0.5,
                            "folletto" =>	1
                        ),

        "fuoco" =>		array(
                            "normale" =>	1,
                            "fuoco" => 		0.5,
                            "acqua" => 		0.5,
                            "elettro" => 	1,
                            "erba" => 		2,
                            "ghiaccio" => 	2,
                            "lotta" => 		1,
                            "veleno" => 	1,
                            "terra" => 		1,
                            "volante" => 	1,
                            "psico" => 		1,
                            "coleottero" => 2,
                            "roccia" => 	0.5,
                            "spettro" => 	1,
                            "drago" => 		0.5,
                            "buio" => 		1,
                            "acciaio" =>	2,
                            "folletto" =>	1
                        ),

        "acqua" =>		array(
                            "normale" =>	1,
                            "fuoco" => 		2,
                            "acqua" => 		0.5,
                            "elettro" => 	1,
                            "erba" => 		0.5,
                            "ghiaccio" => 	1,
                            "lotta" => 		1,
                            "veleno" => 	1,
                            "terra" => 		2,
                            "volante" => 	1,
                            "psico" => 		1,
                            "coleottero" => 1,
                            "roccia" => 	2,
                            "spettro" => 	1,
                            "drago" => 		0.5,
                            "buio" => 		1,
                            "acciaio" =>	1,
                            "folletto" =>	1
                        ),

        "elettro" =>	array(
                            "normale" =>	1,
                            "fuoco" => 		1,
                            "acqua" => 		2,
                            "elettro" => 	0.5,
                            "erba" => 		0.5,
                            "ghiaccio" => 	1,
                            "lotta" => 		1,
                            "veleno" => 	1,
                            "terra" => 		0,
                            "volante" => 	2,
                            "psico" => 		1,
                            "coleottero" => 1,
                            "roccia" => 	1,
                            "spettro" => 	1,
                            "drago" => 		0.5,
                            "buio" => 		1,
                            "acciaio" =>	1,
                            "folletto" =>	1
                        ),

        "erba" =>		array(
                            "normale" =>	1,
                            "fuoco" => 		0.5,
                            "acqua" => 		2,
                            "elettro" => 	1,
                            "erba" => 		0.5,
                            "ghiaccio" => 	1,
                            "lotta" => 		1,
                            "veleno" => 	0.5,
                            "terra" => 		2,
                            "volante" => 	0.5,
                            "psico" => 		1,
                            "coleottero" => 0.5,
                            "roccia" => 	2,
                            "spettro" => 	1,
                            "drago" => 		0.5,
                            "buio" => 		1,
                            "acciaio" =>	0.5,
                            "folletto" =>	1
                        ),

        "ghiaccio" =>	array(
                            "normale" =>	1,
                            "fuoco" => 		0.5,
                            "acqua" => 		0.5,
                            "elettro" => 	1,
                            "erba" => 		2,
                            "ghiaccio" => 	0.5,
                            "lotta" => 		1,
                            "veleno" => 	1,
                            "terra" => 		2,
                            "volante" => 	2,
                            "psico" => 		1,
                            "coleottero" => 1,
                            "roccia" => 	1,
                            "spettro" => 	1,
                            "drago" => 		2,
                            "buio" => 		1,
                            "acciaio" =>	0.5,
                            "folletto" =>	1
                        ),

        "lotta" =>		array(
                            "normale" =>	2,
                            "fuoco" => 		1,
                            "acqua" => 		1,
                            "elettro" => 	1,
                            "erba" => 		1,
                            "ghiaccio" => 	2,
                            "lotta" => 		1,
                            "veleno" => 	0.5,
                            "terra" => 		1,
                            "volante" => 	0.5,
                            "psico" => 		0.5,
                            "coleottero" => 0.5,
                            "roccia" => 	2,
                            "spettro" => 	0,
                            "drago" => 		1,
                            "buio" => 		2,
                            "acciaio" =>	2,
                            "folletto" =>	0.5
                        ),

        "veleno" =>		array(
                            "normale" =>	1,
                            "fuoco" => 		1,
                            "acqua" => 		1,
                            "elettro" => 	1,
                            "erba" => 		2,
                            "ghiaccio" => 	1,
                            "lotta" => 		1,
                            "veleno" => 	0.5,
                            "terra" => 		0.5,
                            "volante" => 	1,
                            "psico" => 		1,
                            "coleottero" => 1,
                            "roccia" => 	0.5,
                            "spettro" => 	0.5,
                            "drago" => 		1,
                            "buio" => 		1,
                            "acciaio" =>	0,
                            "folletto" =>	2
                        ),
        "terra" =>		array(
                            "normale" =>	1,
                            "fuoco" => 		2,
                            "acqua" => 		1,
                            "elettro" => 	2,
                            "erba" => 		0.5,
                            "ghiaccio" => 	1,
                            "lotta" => 		1,
                            "veleno" => 	2,
                            "terra" => 		1,
                            "volante" => 	0,
                            "psico" => 		1,
                            "coleottero" => 0.5,
                            "roccia" => 	2,
                            "spettro" => 	1,
                            "drago" => 		1,
                            "buio" => 		1,
                            "acciaio" =>	2,
                            "folletto" =>	1
                        ),

        "volante" =>	array(
                            "normale" =>	1,
                            "fuoco" => 		1,
                            "acqua" => 		1,
                            "elettro" => 	0.5,
                            "erba" => 		2,
                            "ghiaccio" => 	1,
                            "lotta" => 		2,
                            "veleno" => 	1,
                            "terra" => 		1,
                            "volante" => 	1,
                            "psico" => 		1,
                            "coleottero" => 2,
                            "roccia" => 	0.5,
                            "spettro" => 	1,
                            "drago" => 		1,
                            "buio" => 		1,
                            "acciaio" =>	0.5,
                            "folletto" =>	1
                        ),

        "psico" =>		array(
                            "normale" =>	1,
                            "fuoco" => 		1,
                            "acqua" => 		1,
                            "elettro" => 	1,
                            "erba" => 		1,
                            "ghiaccio" => 	1,
                            "lotta" => 		2,
                            "veleno" => 	2,
                            "terra" => 		1,
                            "volante" => 	1,
                            "psico" => 		0.5,
                            "coleottero" => 1,
                            "roccia" => 	1,
                            "spettro" => 	1,
                            "drago" => 		1,
                            "buio" => 		0,
                            "acciaio" =>	0.5,
                            "folletto" =>	1
                        ),

        "coleottero" =>	array(
                            "normale" =>	1,
                            "fuoco" => 		0.5,
                            "acqua" => 		1,
                            "elettro" => 	1,
                            "erba" => 		2,
                            "ghiaccio" => 	1,
                            "lotta" => 		0.5,
                            "veleno" => 	0.5,
                            "terra" => 		1,
                            "volante" => 	0.5,
                            "psico" => 		2,
                            "coleottero" => 1,
                            "roccia" => 	1,
                            "spettro" => 	0.5,
                            "drago" => 		1,
                            "buio" => 		2,
                            "acciaio" =>	0.5,
                            "folletto" =>	0.5
                        ),

        "roccia" =>		array(
                            "normale" =>	1,
                            "fuoco" => 		2,
                            "acqua" => 		1,
                            "elettro" => 	1,
                            "erba" => 		1,
                            "ghiaccio" => 	2,
                            "lotta" => 		0.5,
                            "veleno" => 	1,
                            "terra" => 		0.5,
                            "volante" => 	2,
                            "psico" => 		1,
                            "coleottero" => 2,
                            "roccia" => 	1,
                            "spettro" => 	1,
                            "drago" => 		1,
                            "buio" => 		1,
                            "acciaio" =>	0.5,
                            "folletto" =>	1
                        ),

        "spettro" =>	array(
                            "normale" =>	0,
                            "fuoco" => 		1,
                            "acqua" => 		1,
                            "elettro" => 	1,
                            "erba" => 		1,
                            "ghiaccio" => 	1,
                            "lotta" => 		1,
                            "veleno" => 	1,
                            "terra" => 		1,
                            "volante" => 	1,
                            "psico" => 		2,
                            "coleottero" => 1,
                            "roccia" => 	1,
                            "spettro" => 	2,
                            "drago" => 		1,
                            "buio" => 		0.5,
                            "acciaio" =>	1,
                            "folletto" =>	1
                        ),

        "drago" =>		array(
                            "normale" =>	1,
                            "fuoco" => 		1,
                            "acqua" => 		1,
                            "elettro" => 	1,
                            "erba" => 		1,
                            "ghiaccio" => 	1,
                            "lotta" => 		1,
                            "veleno" => 	1,
                            "terra" => 		1,
                            "volante" => 	1,
                            "psico" => 		1,
                            "coleottero" => 1,
                            "roccia" => 	1,
                            "spettro" => 	1,
                            "drago" => 		2,
                            "buio" => 		1,
                            "acciaio" =>	0.5,
                            "folletto" =>	0
                        ),

        "buio" =>		array(
                            "normale" =>	1,
                            "fuoco" => 		1,
                            "acqua" => 		1,
                            "elettro" => 	1,
                            "erba" => 		1,
                            "ghiaccio" => 	1,
                            "lotta" => 		0.5,
                            "veleno" => 	1,
                            "terra" => 		1,
                            "volante" => 	1,
                            "psico" => 		2,
                            "coleottero" => 1,
                            "roccia" => 	1,
                            "spettro" => 	2,
                            "drago" => 		1,
                            "buio" => 		0.5,
                            "acciaio" =>	1,
                            "folletto" =>	0.5
                        ),

        "acciaio" =>	array(
                            "normale" =>	1,
                            "fuoco" => 		0.5,
                            "acqua" => 		0.5,
                            "elettro" => 	0.5,
                            "erba" => 		1,
                            "ghiaccio" => 	2,
                            "lotta" => 		1,
                            "veleno" => 	1,
                            "terra" => 		1,
                            "volante" => 	1,
                            "psico" => 		1,
                            "coleottero" => 1,
                            "roccia" => 	2,
                            "spettro" => 	1,
                            "drago" => 		1,
                            "buio" => 		1,
                            "acciaio" =>	0.5,
                            "folletto" =>	2
                        ),
                        
        "folletto" =>	array(
                            "normale" =>	1,
                            "fuoco" => 		0.5,
                            "acqua" => 		1,
                            "elettro" => 	1,
                            "erba" => 		1,
                            "ghiaccio" => 	1,
                            "lotta" => 		2,
                            "veleno" => 	0.5,
                            "terra" => 		1,
                            "volante" => 	1,
                            "psico" => 		1,
                            "coleottero" => 1,
                            "roccia" => 	1,
                            "spettro" => 	1,
                            "drago" => 		2,
                            "buio" => 		2,
                            "acciaio" =>	0.5,
                            "folletto" =>	1
                        )
    );


    //array contenente i vari messaggi a seconda delle efficacie
    const messaggiEfficacie = array(
        100 => 	"Il colpo è andato a segno.",
        200 => 	"Il colpo è stato superefficace!",
        400 =>	"Il colpo è stato iperefficace!!!",
        50  => 	"Il colpo è stato poco efficace!",
        25  =>	"Il colpo è stato scarsamente efficace!!!",
        0   => 	"Il colpo è stato inefficace..."
    );

?>